// apps/frontend/idp-client/src/components/LanguageSwitcher/index.tsx
import { Select } from 'antd';

import { LOCALE_OPTIONS } from '@/constants';
import { useLocaleStore } from '@/stores/locale';

export function LanguageSwitcher() {
  const { currentLocale, setLocale } = useLocaleStore();

  return (
    <Select
      value={currentLocale}
      onChange={setLocale}
      options={LOCALE_OPTIONS}
      style={{ width: 90 }}
      variant='borderless'
    />
  );
}

// apps/frontend/portal/src/components/LanguageSwitcher/index.vue
<template>
  <n-select
    :value="localeStore.currentLocale"
    :options="LOCALE_OPTIONS"
    style="width: 90px"
    @update:value="handleChange"
  />
</template>

<script setup lang="ts">
import { LOCALE_OPTIONS } from '@/constants';
import { useLocaleStore } from '@/stores/locale';
import type { SupportedLocale } from '@/types';

const localeStore = useLocaleStore();

const handleChange = (value: string) => {
  localeStore.setLocale(value as SupportedLocale);
};
</script>
